name: drupoll
recipe: drupal11
config:
  php: "8.3"
  via: apache:2.4
  database: mysql:8.0
  composer_version: 2-latest
  drush: ^13
  webroot: web
services:
  appserver:
    build_as_root:
      # SQLite3 PHP extension for testing
      - add-apt-repository ppa:ondrej/php
      - apt update
      - apt install php8.3-sqlite3
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database